version: "3.7"
services:
  web:
    build: .
    volumes:
        - ./site:/var/www/html
    ports:
      - 80:80
  db:
       image: mysql
       restart: always
       volumes:
           - ./db_data:/var/lib/mysql
       environment:
           MYSQL_ROOT_PASSWORD: 12345
           MYSQL_DATABASE: cars
       ports:
            - 3306:3306